// used to make "select" not show the selection as text
// a purely empty string won't work, but this will
const sneakySpacer = '	';

const pebbleColors = [
  { name: sneakySpacer, color: '#000000' },
  { name: sneakySpacer, color: '#555555' },
  { name: sneakySpacer, color: '#AAAAAA' },
  { name: sneakySpacer, color: '#FFFFFF' },
  { name: sneakySpacer, color: '#AA0000' },
  { name: sneakySpacer, color: '#FF5555' },
  { name: sneakySpacer, color: '#FF0000' },
  { name: sneakySpacer, color: '#AA5555' },
  { name: sneakySpacer, color: '#550000' },
  { name: sneakySpacer, color: '#FFAAAA' },
  { name: sneakySpacer, color: '#FF5500' },
  { name: sneakySpacer, color: '#AA5500' },
  { name: sneakySpacer, color: '#FFAA55' },
  { name: sneakySpacer, color: '#FFAA00' },
  { name: sneakySpacer, color: '#FFFF55' },
  { name: sneakySpacer, color: '#FFFF00' },
  { name: sneakySpacer, color: '#AAAA00' },
  { name: sneakySpacer, color: '#555500' },
  { name: sneakySpacer, color: '#AAAA55' },
  { name: sneakySpacer, color: '#FFFFAA' },
  { name: sneakySpacer, color: '#AAFF00' },
  { name: sneakySpacer, color: '#55AA00' },
  { name: sneakySpacer, color: '#AAFF55' },
  { name: sneakySpacer, color: '#55FF00' },
  { name: sneakySpacer, color: '#005500' },
  { name: sneakySpacer, color: '#00AA00' },
  { name: sneakySpacer, color: '#00FF00' },
  { name: sneakySpacer, color: '#AAFFAA' },
  { name: sneakySpacer, color: '#55AA55' },
  { name: sneakySpacer, color: '#55FF55' },
  { name: sneakySpacer, color: '#00FF55' },
  { name: sneakySpacer, color: '#00AA55' },
  { name: sneakySpacer, color: '#55FFAA' },
  { name: sneakySpacer, color: '#00FFAA' },
  { name: sneakySpacer, color: '#55AAAA' },
  { name: sneakySpacer, color: '#55FFFF' },
  { name: sneakySpacer, color: '#005555' },
  { name: sneakySpacer, color: '#AAFFFF' },
  { name: sneakySpacer, color: '#00AAAA' },
  { name: sneakySpacer, color: '#00FFFF' },
  { name: sneakySpacer, color: '#00AAFF' },
  { name: sneakySpacer, color: '#0055AA' },
  { name: sneakySpacer, color: '#55AAFF' },
  { name: sneakySpacer, color: '#0055FF' },
  { name: sneakySpacer, color: '#0000AA' },
  { name: sneakySpacer, color: '#5555FF' },
  { name: sneakySpacer, color: '#000055' },
  { name: sneakySpacer, color: '#AAAAFF' },
  { name: sneakySpacer, color: '#5555AA' },
  { name: sneakySpacer, color: '#0000FF' },
  { name: sneakySpacer, color: '#5500FF' },
  { name: sneakySpacer, color: '#AA55FF' },
  { name: sneakySpacer, color: '#5500AA' },
  { name: sneakySpacer, color: '#AA00FF' },
  { name: sneakySpacer, color: '#AA55AA' },
  { name: sneakySpacer, color: '#550055' },
  { name: sneakySpacer, color: '#FF55FF' },
  { name: sneakySpacer, color: '#FF00FF' },
  { name: sneakySpacer, color: '#FFAAFF' },
  { name: sneakySpacer, color: '#AA00AA' },
  { name: sneakySpacer, color: '#FF00AA' },
  { name: sneakySpacer, color: '#FF55AA' },
  { name: sneakySpacer, color: '#AA0055' },
  { name: sneakySpacer, color: '#FF0055' },
];

export default pebbleColors;