// used to make "select" not show the selection as text
// a purely empty string won't work, but this will
const sneakySpacer = '	';

const pebbleColors = [
{ name: sneakySpacer, color: '#000000' },
{ name: sneakySpacer, color: '#555555' },
{ name: sneakySpacer, color: '#AAAAAA' },
{ name: sneakySpacer, color: '#FFFFFF' },
{ name: sneakySpacer, color: '#550000' },
{ name: sneakySpacer, color: '#AA5555' },
{ name: sneakySpacer, color: '#AA0000' },
{ name: sneakySpacer, color: '#FFAAAA' },
{ name: sneakySpacer, color: '#FF5555' },
{ name: sneakySpacer, color: '#FF0000' },
{ name: sneakySpacer, color: '#FF5500' },
{ name: sneakySpacer, color: '#AA5500' },
{ name: sneakySpacer, color: '#FFAA55' },
{ name: sneakySpacer, color: '#FFAA00' },
{ name: sneakySpacer, color: '#555500' },
{ name: sneakySpacer, color: '#AAAA55' },
{ name: sneakySpacer, color: '#AAAA00' },
{ name: sneakySpacer, color: '#FFFFAA' },
{ name: sneakySpacer, color: '#FFFF55' },
{ name: sneakySpacer, color: '#FFFF00' },
{ name: sneakySpacer, color: '#AAFF00' },
{ name: sneakySpacer, color: '#55AA00' },
{ name: sneakySpacer, color: '#AAFF55' },
{ name: sneakySpacer, color: '#55FF00' },
{ name: sneakySpacer, color: '#005500' },
{ name: sneakySpacer, color: '#55AA55' },
{ name: sneakySpacer, color: '#00AA00' },
{ name: sneakySpacer, color: '#AAFFAA' },
{ name: sneakySpacer, color: '#55FF55' },
{ name: sneakySpacer, color: '#00FF00' },
{ name: sneakySpacer, color: '#00FF55' },
{ name: sneakySpacer, color: '#00AA55' },
{ name: sneakySpacer, color: '#55FFAA' },
{ name: sneakySpacer, color: '#00FFAA' },
{ name: sneakySpacer, color: '#005555' },
{ name: sneakySpacer, color: '#55AAAA' },
{ name: sneakySpacer, color: '#00AAAA' },
{ name: sneakySpacer, color: '#AAFFFF' },
{ name: sneakySpacer, color: '#55FFFF' },
{ name: sneakySpacer, color: '#00FFFF' },
{ name: sneakySpacer, color: '#00AAFF' },
{ name: sneakySpacer, color: '#0055AA' },
{ name: sneakySpacer, color: '#55AAFF' },
{ name: sneakySpacer, color: '#0055FF' },
{ name: sneakySpacer, color: '#000055' },
{ name: sneakySpacer, color: '#5555AA' },
{ name: sneakySpacer, color: '#0000AA' },
{ name: sneakySpacer, color: '#AAAAFF' },
{ name: sneakySpacer, color: '#5555FF' },
{ name: sneakySpacer, color: '#0000FF' },
{ name: sneakySpacer, color: '#5500FF' },
{ name: sneakySpacer, color: '#5500AA' },
{ name: sneakySpacer, color: '#AA55FF' },
{ name: sneakySpacer, color: '#AA00FF' },
{ name: sneakySpacer, color: '#550055' },
{ name: sneakySpacer, color: '#AA55AA' },
{ name: sneakySpacer, color: '#AA00AA' },
{ name: sneakySpacer, color: '#FFAAFF' },
{ name: sneakySpacer, color: '#FF55FF' },
{ name: sneakySpacer, color: '#FF00FF' },
{ name: sneakySpacer, color: '#FF00AA' },
{ name: sneakySpacer, color: '#AA0055' },
{ name: sneakySpacer, color: '#FF55AA' },
{ name: sneakySpacer, color: '#FF0055' },
];

const colorNames = {
'#000000': 'Black',
'#555555': 'Dark Gray',
'#AAAAAA': 'Light Gray',
'#FFFFFF': 'White',
'#550000': 'Bulgarian Rose',
'#AA5555': 'Rose Vale',
'#AA0000': 'Dark Candy Apple Red',
'#FFAAAA': 'Melon',
'#FF5555': 'Sunset Orange',
'#FF0000': 'Red',
'#FF5500': 'Orange',
'#AA5500': 'Windsor Tan',
'#FFAA55': 'Rajah',
'#FFAA00': 'Chrome Yellow',
'#555500': 'Army Green',
'#AAAA55': 'Brass',
'#AAAA00': 'Limerick',
'#FFFFAA': 'Pastel Yellow',
'#FFFF55': 'Icterine',
'#FFFF00': 'Yellow',
'#AAFF00': 'Spring Bud',
'#55AA00': 'Kelly Green',
'#AAFF55': 'Inchworm',
'#55FF00': 'Bright Green',
'#005500': 'Dark Green',
'#55AA55': 'May Green',
'#00AA00': 'Islamic Green',
'#AAFFAA': 'Mint Green',
'#55FF55': 'Screamin\' Green',
'#00FF00': 'Green',
'#00FF55': 'Malachite',
'#00AA55': 'Jaeger Green',
'#55FFAA': 'Medium Aquamarine',
'#00FFAA': 'Medium Spring Green',
'#005555': 'Midnight Green',
'#55AAAA': 'Cadet Blue',
'#00AAAA': 'Tiffany Blue',
'#AAFFFF': 'Celeste',
'#55FFFF': 'Electric Blue',
'#00FFFF': 'Cyan',
'#00AAFF': 'Vivid Cerulean',
'#0055AA': 'Cobalt Blue',
'#55AAFF': 'Picton Blue',
'#0055FF': 'Blue Moon',
'#000055': 'Oxford Blue',
'#5555AA': 'Liberty',
'#0000AA': 'Duke Blue',
'#AAAAFF': 'Baby Blue Eyes',
'#5555FF': 'Very Light Blue',
'#0000FF': 'Blue',
'#5500FF': 'Electric Ultramarine',
'#5500AA': 'Indigo',
'#AA55FF': 'Lavender Indigo',
'#AA00FF': 'Vivid Violet',
'#550055': 'Imperial Purple',
'#AA55AA': 'Purpureus',
'#AA00AA': 'Purple',
'#FFAAFF': 'Rich Brilliant Lavender',
'#FF55FF': 'Shocking Pink',
'#FF00FF': 'Magenta',
'#FF00AA': 'Fashion Magenta',
'#AA0055': 'Jazzberry Jam',
'#FF55AA': 'Brilliant Rose',
'#FF0055': 'Folly',
};

export { pebbleColors, colorNames, sneakySpacer };