const language_names = {
    "en_US": ["English", "English"],
    "fr_FR": ["French", "Français"],
    "de_DE": ["German", "Deutsch"],
    "es_ES": ["Spanish", "Español"],
    "it_IT": ["Italian", "Italiano"],
    "nl_NL": ["Dutch", "Nederlands"],
    "tr_TR": ["Turkish", "Türkçe"],
    "cs_CZ": ["Czech", "Čeština"],
    "pt_BR": ["Portuguese", "Português"],
    "el_GR": ["Greek", "Ελληνικά"],
    "sv_SE": ["Swedish", "Svenska"],
    "pl_PL": ["Polish", "Polski"],
    "sk_SK": ["Slovak", "Slovenčina"],
    "vi_VN": ["Vietnamese", "Tiếng Việt"],
    "ro_RO": ["Romanian", "Română"],
    "ca_CA": ["Catalan", "Català"],
    "no_NO": ["Norwegian", "Norsk"],
    "ru_RU": ["Russian", "Русский"],
    "et_EE": ["Estonian", "Eesti"],
    "eu_ES": ["Basque", "Euskara"],
    "fi_FI": ["Finnish", "Suomi"],
    "da_DK": ["Danish", "Dansk"],
    "lt_LT": ["Lithuanian", "Lietuviškai"],
    "sl_SI": ["Slovenian", "Slovenščina"],
    "hu_HU": ["Hungarian", "Magyar"],
    "hr_HR": ["Croatian", "Hrvatski"],
    "ga_IE": ["Irish", "Gaeilge"],
    "lv_LV": ["Latvian", "Latviešu"],
    "sr_SP": ["Serbian", "Srpski"],
    "zh_CN": ["Chinese", "中文"],
    "id_ID": ["Indonesian", "Bahasa Indonesia"],
    "uk_UA": ["Ukranian", "Українська"],
    "cy_GB": ["Welsh", "Cymraeg"],
    "gl_ES": ["Gallacian", "Galego"],
    "jp_JP": ["Japanese", "日本語"],
    "ko_KR": ["Korean", "한국어"],
    "he_IL": ["Hebrew", "עברית"],
    "ar_AR": ["Arabic", "العربية"]
};

const weekday_names = {
	"en_US": ["SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"],
	"fr_FR": ["DIM", "LUN", "MAR", "MER", "JEU", "VEN", "SAM"],
	"de_DE": ["SO",  "MO",  "DI",  "MI",  "DO",  "FR",  "SA"],
	"es_ES": ["DOM", "LUN", "MAR", "MIÉ", "JUE", "VIE", "SÁB"],
	"it_IT": ["DOM", "LUN", "MAR", "MER", "GIO", "VEN", "SAB"],
	"nl_NL": ["ZO",  "MA",  "DI",  "WO",  "DO",  "VR",  "ZA"],
	"tr_TR": ["PAZ", "PTS", "SAL", "ÇAR", "PER", "CUM", "CTS"],
	"cs_CZ": ["NE",  "PO",  "ÚT",  "ST",  "ČT",  "PÁ",  "SO"],
	"pt_BR": ["DOM", "SEG", "TER", "QUA", "QUI", "SEX", "SÁB"],
	"el_GR": ["ΚΥΡ", "ΔΕΥ", "ΤΡΙ", "ΤΕΤ", "ΠΕΜ", "ΠΑΡ", "ΣΑΒ"],
	"sv_SE": ["SÖN", "MÅN", "TIS", "ONS", "TOR", "FRE", "LÖR"],
	"pl_PL": ["NDZ", "PON", "WTO", "ŚRO", "CZW", "PIĄ", "SOB"],
	"sk_SK": ["NE", "PO", "UT", "ST", "ŠT", "PI", "SO"],
	"vi_VN": ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
	"ro_RO": ["DUM", "LUN", "MAR", "MIE", "JOI", "VIN", "SÂM"],
	"ca_CA": ["DG", "DL", "DT", "DC", "DJ", "DV", "DS"],
	"no_NO": ["SØN", "MAN", "TIR", "ONS", "TOR", "FRE", "LØR"],
	"ru_RU": ["ВС", "ПН", "ВТ", "СР", "ЧТ", "ПТ", "СБ"],
	"et_EE": ["P", "E", "T", "K", "N", "R", "L"],
	"eu_ES": ["IG", "AL", "AR", "AZ", "OG", "OL", "LR"],
	"fi_FI": ["SU", "MA", "TI", "KE", "TO", "PE", "LA"],
	"da_DK": ["SØN", "MAN", "TIR", "ONS", "TOR", "FRE", "LØR"],
	"lt_LT": ["SEK", "PIR", "ANT", "TRE", "KET", "PEN", "ŠEŠ"],
	"sl_SI": ["NED", "PON", "TOR", "SRE", "ČET", "PET", "SOB"],
	"hu_HU": ["VAS", "HÉT", "KED", "SZE", "CSÜ", "PÉN", "SZO"],
	"hr_HR": ["NED", "PON", "UTO", "SRE", "ČET", "PET", "SUB"],
	"ga_IE": ["DOM", "LUA", "MÁI", "CÉA", "DÉA", "AOI", "SAT"],
	"lv_LV": ["SVĒ", "PIR", "OTR", "TRE", "CET", "PIE", "SES"],
	"sr_SP": ["NE", "PO", "UT", "SR", "ČE", "PE", "SU"],
	"zh_CN": ["日", "一", "二", "三", "四", "五", "六"],
	"id_ID": ["MIN", "SEN",  "SEL", "RAB", "KAM", "JUM", "SAB"],
	"uk_UA": ["НД", "ПН", "ВТ",  "СР", "ЧТ", "ПТ", "СБ"],
	"cy_GB": ["SUL", "LLN", "MAW", "MER", "IAU", "GWE", "SAD"],
	"gl_ES": ["DOM", "LUN", "MAR", "MER", "XOV", "VEN", "SAB"],
	"jp_JP": ["日", "月", "火", "水", "木", "金", "土"],
	"ko_KR": ["일", "월", "화", "수", "목", "금", "토"],
	"he_IL": ["א", "ב", "ג", "ד", "ה", "ו", "ש"],
  "ar_AR": ["أحد", "إثن", "ثلاث", "أرب", "خمس", "جمع", "سبت"]
};

const month_names = {
    "en_US":["JAN","FEB","MAR","APR","MAY","JUN","JUL","AUG","SEP","OCT","NOV","DEC"],
    "fr_FR":["JAN","FÉV","MAR","AVR","MAI","JUI","JUL","AOÛ","SEP","OCT","NOV","DÉC"],
    "de_DE":["JAN","FEB","MÄR","APR","MAI","JUN","JUL","AUG","SEP","OKT","NOV","DEZ"],
    "es_ES":["ENE","FEB","MAR","ABR","MAY","JUN","JUL","AGO","SEP","OCT","NOV","DIC"],
    "it_IT":["GEN","FEB","MAR","APR","MAG","GIU","LUG","AGO","SET","OTT","NOV","DIC"],
    "nl_NL":["JAN","FEB","MRT","APR","MEI","JUN","JUL","AUG","SEP","OKT","NOV","DEC"],
    "tr_TR":["OCA","ŞUB","MAR","NİS","MAY","HAZ","TEM","AĞU","EYL","EKİ","KAS","ARA"],
    "cs_CZ":["LED","ÚNO","BŘE","DUB","KVĚ","ČRV","ČVC","SRP","ZÁŘ","ŘÍJ","LIS","PRO"],
    "pt_BR":["JAN","FEV","MAR","ABR","MAI","JUN","JUL","AGO","SET","OUT","NOV","DEZ"],
    "el_GR":["ΙΑΝ","ΦΕΒ","ΜΑΡ","ΑΠΡ","ΜΑΪ","ΙΟΝ","ΙΟΛ","ΑΥΓ","ΣΕΠ","ΟΚΤ","ΝΟΕ","ΔΕΚ"],
    "sv_SE":["JAN","FEB","MAR","APR","MAJ","JUN","JUL","AUG","SEP","OKT","NOV","DEC"],
    "pl_PL":["STY","LUT","MAR","KWI","MAJ","CZE","LIP","SIE","WRZ","PAŹ","LIS","GRU"],
    "sk_SK":["JAN","FEB","MAR","APR","MÁJ","JÚN","JÚL","AUG","SEP","OKT","NOV","DEC"],
    "vi_VN":["Th1","Th2","Th3","Th4","Th5","Th6","Th7","Th8","Th9","T10","T11","T12"],
    "ro_RO":["IAN","FEB","MAR","APR","MAI","IUN","IUL","AUG","SEP","OCT","NOI","DEC"],
    "ca_CA":["GEN","FEB","MAR","ABR","MAI","JUN","JUL","AGO","SET","OCT","NOV","DES"],
    "no_NO":["JAN","FEB","MAR","APR","MAI","JUN","JUL","AUG","SEP","OKT","NOV","DES"],
    "ru_RU":["ЯНВ","ФЕВ","МАР","АПР","МАЙ","ИЮН","ИЮЛ","АВГ","СЕН","ОКТ","НОЯ","ДЕК"],
    "et_EE":["JAN","VEB","MÄR","APR","MAI","JUN","JUL","AUG","SEP","OKT","NOV","DET"],
    "eu_ES":["URT","OTS","MAR","API","MAI","EKA","UZT","ABU","IRA","URR","AZA","ABE"],
    "fi_FI":["TAM","HEL","MAA","HUH","TOU","KES","HEI","ELO","SYY","LOK","MAR","JOU"],
    "da_DK":["JAN","FEB","MAR","APR","MAJ","JUN","JUL","AUG","SEP","OKT","NOV","DEC"],
    "lt_LT":["SAU","VAS","KOV","BAL","GEG","BIR","LIE","RUG","RGS","SPA","LAP","GRU"],
    "sl_SI":["JAN","FEB","MAR","APR","MAJ","JUN","JUL","AVG","SEP","OKT","NOV","DEC"],
    "hu_HU":["JAN","FEB","MÁR","ÁPR","MÁJ","JÚN","JÚL","AUG","SZE","OKT","NOV","DEC"],
    "hr_HR":["SIJ","VEL","OŽU","TRA","SVI","LIP","SRP","KOL","RUJ","LIS","STU","PRO"],
    "ga_IE":["EAN","FEA","MÁR","AIB","BEA","MEI","IÚI","LÚN","MFÓ","DFÓ","SAM","NOL"],
    "lv_LV":["JAN","FEB","MAR","APR","MAI","JŪN","JŪL","AUG","SEP","OKT","NOV","DEC"],
    "sr_SP":["JAN","FEB","MAR","APR","MAJ","JUN","JUL","AVG","SEP","OKT","NOV","DEC"],
    "zh_CN":["1","2","3","4","5","6","7","8","9","10","11","12"],
    "id_ID":["JAN","FEB","MAR","APR","MEI","JUN","JUL","AGU","SEP","OKT","NOV","DES"],
    "uk_UA":["СІЧ","ЛЮТ","БЕР","КВІ","ТРА","ЧЕР","ЛИП","СЕР","ВЕР","ЖОВ","ЛИС","ГРУ"],
    "cy_GB":["ION","CHW","MAW","EBR","MAI","MEH","GOR","AWS","MED","HYD","TCH","RHA"],
    "gl_ES":["XAN","FEB","MAR","ABR","MAI","XUÑ","XUL","AGO","SET","OUT","NOV","NAD"],
    "jp_JP":["1月","2月","3月","4月","5月","6月","7月","8月","9月","10月","11月","12月"],
    "ko_KR":["1월","2월","3월","4월","5월","6월","7월","8월","9월","10월","11월","12월"],
    "he_IL":["ינו","פבר","מרץ","אפר","מאי","יונ","יול","אוג","ספט","אוק","נוב","דצמ"],
    "ar_AR":["JAN","FEB","MAR","APR","MAY","JUN","JUL","AUG","SEP","OCT","NOV","DEC"]
};


export { language_names, weekday_names, month_names };